---
channel: stable
addons:
  cups-airprint:
    repository: joschi-ha/addon-cups-airprint
    target: cups-airprint
    image: ghcr.io/joschi-ha/cups-airprint/{arch}
  sane-scanner:
    repository: joschi-ha/addon-sane
    target: sane-scanner
    image: ghcr.io/joschi-ha/sane-scanner/{arch}
